#
# Copyright (c) 2025 Nordic Semiconductor
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NRF_SENSOR_ENGINE=y
CONFIG_NRFX_SPIM=y
CONFIG_NRFX_SPIS=y
CONFIG_NRF_SYS_EVENT=y
#CONFIG_LOG=y
CONFIG_ASSERT=y
#CONFIG_NRF_CPU_LOAD=y
# to not start uart RX
CONFIG_UART_ASYNC_API=y
